// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/observer/api/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockDeliveryInsightsService is an autogenerated mock type for the DeliveryInsightsService type
type MockDeliveryInsightsService struct {
	mock.Mock
}

type MockDeliveryInsightsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeliveryInsightsService) EXPECT() *MockDeliveryInsightsService_Expecter {
	return &MockDeliveryInsightsService_Expecter{mock: &_m.Mock}
}

// QueryDoraDeployments provides a mock function with given fields: ctx, req
func (_m *MockDeliveryInsightsService) QueryDoraDeployments(ctx context.Context, req gen.DoraDeploymentsQueryRequest) (*gen.DoraDeploymentsQueryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryDoraDeployments")
	}

	var r0 *gen.DoraDeploymentsQueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gen.DoraDeploymentsQueryRequest) (*gen.DoraDeploymentsQueryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gen.DoraDeploymentsQueryRequest) *gen.DoraDeploymentsQueryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.DoraDeploymentsQueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gen.DoraDeploymentsQueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeliveryInsightsService_QueryDoraDeployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryDoraDeployments'
type MockDeliveryInsightsService_QueryDoraDeployments_Call struct {
	*mock.Call
}

// QueryDoraDeployments is a helper method to define mock.On call
//   - ctx context.Context
//   - req gen.DoraDeploymentsQueryRequest
func (_e *MockDeliveryInsightsService_Expecter) QueryDoraDeployments(ctx interface{}, req interface{}) *MockDeliveryInsightsService_QueryDoraDeployments_Call {
	return &MockDeliveryInsightsService_QueryDoraDeployments_Call{Call: _e.mock.On("QueryDoraDeployments", ctx, req)}
}

func (_c *MockDeliveryInsightsService_QueryDoraDeployments_Call) Run(run func(ctx context.Context, req gen.DoraDeploymentsQueryRequest)) *MockDeliveryInsightsService_QueryDoraDeployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gen.DoraDeploymentsQueryRequest))
	})
	return _c
}

func (_c *MockDeliveryInsightsService_QueryDoraDeployments_Call) Return(_a0 *gen.DoraDeploymentsQueryResponse, _a1 error) *MockDeliveryInsightsService_QueryDoraDeployments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeliveryInsightsService_QueryDoraDeployments_Call) RunAndReturn(run func(context.Context, gen.DoraDeploymentsQueryRequest) (*gen.DoraDeploymentsQueryResponse, error)) *MockDeliveryInsightsService_QueryDoraDeployments_Call {
	_c.Call.Return(run)
	return _c
}

// QueryDoraMetrics provides a mock function with given fields: ctx, req
func (_m *MockDeliveryInsightsService) QueryDoraMetrics(ctx context.Context, req gen.DoraMetricsQueryRequest) (*gen.DoraMetricsQueryResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryDoraMetrics")
	}

	var r0 *gen.DoraMetricsQueryResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, gen.DoraMetricsQueryRequest) (*gen.DoraMetricsQueryResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, gen.DoraMetricsQueryRequest) *gen.DoraMetricsQueryResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.DoraMetricsQueryResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, gen.DoraMetricsQueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeliveryInsightsService_QueryDoraMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryDoraMetrics'
type MockDeliveryInsightsService_QueryDoraMetrics_Call struct {
	*mock.Call
}

// QueryDoraMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - req gen.DoraMetricsQueryRequest
func (_e *MockDeliveryInsightsService_Expecter) QueryDoraMetrics(ctx interface{}, req interface{}) *MockDeliveryInsightsService_QueryDoraMetrics_Call {
	return &MockDeliveryInsightsService_QueryDoraMetrics_Call{Call: _e.mock.On("QueryDoraMetrics", ctx, req)}
}

func (_c *MockDeliveryInsightsService_QueryDoraMetrics_Call) Run(run func(ctx context.Context, req gen.DoraMetricsQueryRequest)) *MockDeliveryInsightsService_QueryDoraMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(gen.DoraMetricsQueryRequest))
	})
	return _c
}

func (_c *MockDeliveryInsightsService_QueryDoraMetrics_Call) Return(_a0 *gen.DoraMetricsQueryResponse, _a1 error) *MockDeliveryInsightsService_QueryDoraMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeliveryInsightsService_QueryDoraMetrics_Call) RunAndReturn(run func(context.Context, gen.DoraMetricsQueryRequest) (*gen.DoraMetricsQueryResponse, error)) *MockDeliveryInsightsService_QueryDoraMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeliveryInsightsService creates a new instance of MockDeliveryInsightsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveryInsightsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveryInsightsService {
	mock := &MockDeliveryInsightsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
